### ISSUE TITLE
`ridk version` could display which `path` Ruby was installed

### ISSUE THREAD

**Issue by luislavena** [larskanis/rubyinstaller2#20]
Current `ridk version` displays path information for MSYS2 but not for Ruby itself:

```
C:\Users\Luis>ridk version
---
ruby:
  version: 2.4.0
  platform: x64-mingw32
ruby_installer:
  version: 2.4.0-8
  git_commit: ec1919d
msys2:
  path: c:\msys64
  title: MSYS2 64bit
  version: '20161025'
cc: x86_64-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 6.3.0
sh: GNU bash, version 4.3.46(2)-release (x86_64-pc-msys)
```

I believe that adding information about which `path` ruby was installed will be helpful to debug issues (specially if user installed in a path with spaces)

I can send a pull request, wanted to confirm this is :+1:  or :-1: 

Thank you. :heart: :heart: :heart:
