### ISSUE TITLE
Suggest `ridk install` when MSYS2 is not detected during gem installation

### ISSUE THREAD

**Issue by luislavena** [larskanis/rubyinstaller2#22]
## What problems are you experiencing?

Given no MSYS2 was previously installed, attempt to `gem install` something that requires a compiler presents the following message:

```
C:\Users\Luis>gem install sqlite3 --platform=ruby
Fetching: sqlite3-1.3.13.gem (100%)
MSYS2 could not be found.
Please download and install MSYS2 from https://msys2.github.io/
```

Considering `ridk` was introduced to simplify MSYS2 installation, it might be better recommend it instead of a link to the MSYS2 website.

## What's the output from `ridk version`?

```yaml
---
ruby:
  path: C:/Ruby24-x64
  version: 2.4.0
  platform: x64-mingw32
ruby_installer:
  version: 2.4.0-8
  git_commit: c55856f
```

---

Submitting this to gather feedback and suggestions for the displayed message.

Thank you. ❤️ ❤️ ❤️
